# Generated by Django 6.1.1 on 2026-09-10 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='hint',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
